services:
  
  django:
    build: 
      context: ./server_sniffer
      ssh: 
        - default
    command: python3 manage.py runserver
    #volumes:
    #- /home/giuseppe-daquanno/.ssh:/home/server_sniffer/.ssh
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data: