services:
  
  django:
    build: ./docker/django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - django_data:/home/server_sniffer/server_sniffer
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  cron:
    build: ./docker/cron
    command: bash -c "chown -R root:root /root/.ssh && 
                      printenv | grep -v "no_proxy" >> /etc/environment &&
                      cron -f"
    volumes:
      - django_data:/usr/src/server_sniffer:rw
      - ./:/home/test/server_sniffer/
      - .ssh:/root/.ssh:rw
    env_file:
      - ./.env
    depends_on:
      - mongo
      - django

volumes:
  django_data:
  mongo_data:
  ssh_data: