services:
  django:
    build: 
      context: ./server_sniffer
      ssh: 
        - default
    command: cat test #python manage.py runserver 0.0.0.0:8000
    volumes:
    - /home/giuseppe-daquanno/.ssh:/home/server_sniffer/.ssh
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env
