# Generated by Django 4.1.1 on 2022-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_arch', models.CharField(max_length=200, verbose_name='Architettura CPU')),
                ('cpu_model', models.CharField(max_length=200, verbose_name='Modello CPU')),
                ('cpu_count', models.IntegerField(verbose_name='Numero CPU')),
                ('cpu_cores', models.IntegerField(verbose_name='Numero cores')),
                ('cpu_proc_units', models.IntegerField(verbose_name='Numero processing units')),
                ('cpu_vcpus', models.IntegerField(verbose_name='Numero CPU virtuali')),
                ('total_ram', models.IntegerField(verbose_name='RAM totale')),
                ('storage', models.JSONField(verbose_name='Dispositivi per storage')),
                ('interfaces', models.JSONField(verbose_name='Interfacce di rete')),
                ('mount_points', models.JSONField(verbose_name='Punti di mount')),
            ],
        ),
    ]
